easy_slam_product:
    resource: "@EasySlamProductBundle/Controller/"
    type:     annotation
    prefix:   /

easy_slam_user:
    resource: "@EasySlamUserBundle/Controller/"
    type:     annotation
    prefix:   /

easy_slam_main:
    resource: "@EasySlamMainBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
