services:
    sonata.admin.user:
        class: EasySlam\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Utilisateurs" }
        arguments:
            - ~
            - EasySlam\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamUserBundle]]

    sonata.admin.fournisseur:
            class: EasySlam\UserBundle\Admin\FournisseurAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Fournisseurs" }
            arguments:
                - ~
                - EasySlam\UserBundle\Entity\Fournisseur
                - ~
            calls:
                - [ setTranslationDomain, [EasySlamUserBundle]]
